
aerialship_saml_sp.security.login:
    pattern: /login_saml
    defaults: { _controller: "AerialShipSamlSPBundle:Security:login" }

aerialship_saml_sp.security.check:
    pattern: /login_check_saml
    defaults: { _controller: "AerialShipSamlSPBundle:Security:check" }

aerialship_saml_sp.security.logout:
    pattern: /logout_saml
    defaults: { _controller: "AerialShipSamlSPBundle:Security:logout" }

