
parameters:
    security.authentication.provider.aerial_ship_saml_sp.class: AerialShip\SamlSPBundle\Security\Authentication\Provider\SamlSpProvider
    security.authentication.listener.aerial_ship_saml_sp.class: AerialShip\SamlSPBundle\Security\Listener\SamlSpListener
    aerial_ship_saml_sp.relying_party.authenticate.class: AerialShip\SamlSPBundle\Bridge\Authenticate
    aerial_ship_saml_sp.relying_party.assertion_consumer.class: AerialShip\SamlSPBundle\Bridge\AssertionConsumer
    aerial_ship_saml_sp.relying_party.collection.class: AerialShip\SamlSPBundle\RelyingParty\RelyingPartyCollection
    aerial_ship_saml_sp.entity_descriptor_provider.sp.class: AerialShip\SamlSPBundle\Config\EntityDescriptorFileProvider
    aerial_ship_saml_sp.entity_descriptor_provider.idp.class: AerialShip\SamlSPBundle\Config\EntityDescriptorFileProvider
    aerial_ship_saml_sp.sp_meta_provider.class: AerialShip\SamlSPBundle\Config\SpMetaConfigProvider

services:

    security.authentication.provider.aerial_ship_saml_sp:
        class: %security.authentication.provider.aerial_ship_saml_sp.class%
        public: false
        abstract: true
        arguments: [~]


    security.authentication.listener.aerial_ship_saml_sp:
        class: %security.authentication.listener.aerial_ship_saml_sp.class%
        parent: security.authentication.listener.abstract
        public: false
        abstract: true


    aerial_ship_saml_sp.relying_party.authenticate:
        class: %aerial_ship_saml_sp.relying_party.authenticate.class%
        arguments:
            - @aerial_ship_saml_sp.entity_descriptor_provider.sp
            - @aerial_ship_saml_sp.entity_descriptor_provider.idp
        public: false

    aerial_ship_saml_sp.relying_party.assertion_consumer:
        class: %aerial_ship_saml_sp.relying_party.assertion_consumer.class%
        arguments: []
        public: false

    aerial_ship_saml_sp.relying_party.default:
        class: %aerial_ship_saml_sp.relying_party.collection.class%
        calls:
            - [append, [@aerial_ship_saml_sp.relying_party.authenticate]]
            - [append, [@aerial_ship_saml_sp.relying_party.assertion_consumer]]
        public: false



